### PR TITLE
Feature/user class

### PR DESCRIPTION
**Pull request by KarrarQ**
## What does this merge do? Check all that apply.
- [X] Adds a new feature
- [ ] Improves an existing feature
- [ ] Fixes a bug
- [ ] Cleans up (logs, tests, etc.)

## How has this been tested?
-Yes

## Description:
Briefly, but clearly describe what you did, and explain any new code.
-Finished UserClass and TTD

## Issues:
Are there any concerns, issues, or bugs in this branch? If so describe them.
-No

## Where to find Changes:
Files:_____User Class__________
Methods:______________
line Numbers if possible: ________________________________________ 

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have used tests to prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my change

### CODE REVIEW

**Review by BHaddad1 — APPROVED** [review]
Looks great! Thanks Karrar!

**Review by KarimAl-Rashdan — APPROVED** [review]
This looks good.No bugs detected

**Comment by AndrewCerveny** [comment]
We viewed the class as a group and the User Class looks good.

**Review by AndrewCerveny — APPROVED** [review]
We went over User Class as a group.

**Pull request merged**
