### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by KarrarQ**
Took out the deployable link

## What does this merge do? Check all that apply.
- [ ] Adds a new feature
- [ ] Improves an existing feature
- [X] Fixes a bug
- [ ] Cleans up (logs, tests, etc.)

## Description:
Briefly, but clearly describe what you did, and explain any new code.

## Issues:
Are there any concerns, issues, or bugs in this branch? If so describe them.

## Where to find Changes:
Files:_______________
Methods:______________
line Numbers if possible: ________________________________________ 

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have used tests to prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my change

### CODE REVIEW

**Review by BHaddad1 — APPROVED** [review]
Awesome, thanks Karrar!

**Review by KarimAl-Rashdan — APPROVED** [review]
Looks good Karrar.

**Comment by AndrewCerveny** [comment]
looks good

**Review by BHaddad1 — APPROVED** [review]
Second time is the charm.

**Review by AndrewCerveny — APPROVED** [review]
Nice! You did a great job!

**Pull request merged**
