### PR TITLE
Feature/karim final refactor

### PR DESCRIPTION
**Pull request by KarimAl-Rashdan**
## What does this merge do? Check all that apply.
- [X ] Adds a new feature
- [X ] Improves an existing feature
- [ ] Fixes a bug
- [X ] Cleans up (logs, tests, etc.)

## How has this been tested?
npm test
## Description:
Briefly, but clearly describe what you did, and explain any new code.
I merged the HTML, CSS, README, and Scripts file to all work together to create a bug free webpage. I fixed the formatting of all files
## Issues:
Are there any concerns, issues, or bugs in this branch? If so describe them.
I did not check all the links to the README. I'm also unsure what comments to delete at the top of the scripts file. Do we want to keep the imports we are not using?
## Where to find Changes:
Files:_HTML, CSS, README, Scripts______________
Methods:______________
line Numbers if possible: ________________________________________ 

## Checklist

- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have used tests to prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass locally with my change

### CODE REVIEW

**Review by KarrarQ — APPROVED** [review]
Looks really good, Great job Karrrim !

**Review by BHaddad1 — APPROVED** [review]
Looks great, thanks Karim.

**Comment by AndrewCerveny** [comment]
Hey, Looked over the branch and made some changes. Got rid of Chart.js, fixed the name in readMe, fixed some sporadic syntax, and lastly created an enable disable button feature for hydro submit. 
I have pushed all the changes up to this branch. I have not merged waiting for your review. Tomorrow 12/12 let me know what you think and I'll be the last reviewer to merge to the main. ThankYou!

**Review by AndrewCerveny — APPROVED** [review]
All of the changes made last night were pushed up to this branch and now can be merged.

**Pull request merged**
